logging:
  level:
    root: INFO
    
server:
  port: 8080
  
spring:

  datasource:
    driverClassName: org.h2.Driver
    password: 1234
    url: jdbc:h2:mem:testdb
    username: sa
    
  h2:
    console:
      enabled: true
      path: /h2-console
