version: '3.8'
services:
  frontend:
    image: poletto-skins-client
    container_name: frontend
    ports:
      - "3000:80" 
    depends_on:
      - poletto-skins-api
    networks:
      - app-network

  poletto-skins-api:
    image: poletto-skins-api
    container_name: poletto-skins-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge