version: '3.8'
services:
  frontend:
    image: crysisprophet1234/poletto-skins-client
    container_name: poletto-skins-frontend
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: crysisprophet1234/poletto-skins-api
    container_name: poletto-skins-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/poletto_skins/.env.compose
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge