name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/poletto_skins/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/poletto_skins/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      LOG_FILE_PATH: ${{ secrets.LOG_FILE_PATH }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SERVER_CONTEXT_PATH: ${{ secrets.SERVER_CONTEXT_PATH }}
      CORS_ALLOWED_ORIGIN: ${{ secrets.CORS_ALLOWED_ORIGIN }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_TIMEOUT: ${{ secrets.JWT_TIMEOUT }}
      CSFLOAT_API_URL: ${{ secrets.CSFLOAT_API_URL }}
      CSFLOAT_API_REFERER: ${{ secrets.CSFLOAT_API_REFERER }}
      CSFLOAT_API_ORIGIN: ${{ secrets.CSFLOAT_API_ORIGIN }}
      STEAM_API_URL: ${{ secrets.STEAM_API_URL }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_COMMUNITY_URL: ${{ secrets.STEAM_COMMUNITY_URL }}
      OPENID_PROVIDERS_STEAM: ${{ secrets.OPENID_PROVIDERS_STEAM }}
      OPENID_RETURN_TO_URL: ${{ secrets.OPENID_RETURN_TO_URL }}
      LOGIN_SUCCESS_URL: ${{ secrets.LOGIN_SUCCESS_URL }}
      LOGIN_FAILURE_URL: ${{ secrets.LOGIN_FAILURE_URL }}

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            .mvn
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}-maven-version-${{ steps.maven-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-maven-wrapper-

      - name: Get Maven Version
        id: maven-version
        run: echo "::set-output name=version::$(mvn -v | grep 'Apache Maven' | awk '{print $3}')"

      - name: Build and Test with Maven
        working-directory: ./backend/poletto_skins/
        run: mvn clean verify --no-transfer-progress
